'use strict';

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


//loop for fibinachi sequence

var fibArr = [1,2];

for (var i = 1; i < 4000000; ++i){
		if (fibArr[fibArr.length-1] + fibArr[fibArr.length-2] < 4000000){
		fibArr.push( fibArr[fibArr.length-1] + fibArr[fibArr.length-2] );
		}
	}

console.log(fibArr);

//add that array together by using an if else statement for numbers that %2 and add together 

var totalOfFibArr = 0;
for (var j = 0; j < fibArr.length; j++){
	if (fibArr[j] % 2 === 0) {
		totalOfFibArr = totalOfFibArr + fibArr[j];
	}
}

console.log(totalOfFibArr);